# Generated by Django 5.0.6 on 2024-06-27 18:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 27, 18, 32, 7, 370460, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favPost', to='api.post'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'post')},
        ),
    ]
