# Generated by Django 5.0.6 on 2024-06-24 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcircles",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="socialcircles",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_social_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialcircles",
            name="desc",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="socialcircles",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
