# Generated by Django 5.0.6 on 2024-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_journalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
