# Generated by Django 5.0.6 on 2024-06-27 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='created_at',
        ),
    ]
