# Generated by Django 5.0.6 on 2024-08-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
