# Generated by Django 5.1.1 on 2024-09-16 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connections_delete_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('post_creation', models.BooleanField(default=False)),
                ('post_like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('social_circle', models.BooleanField(default=False)),
                ('screen_time_alert', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
